import { ThemeType } from '../types'
import playfairDisplay from '../fontfaces/playfair-display'
import poppins from '../fontfaces/poppins'
import pressStart2p from '../fontfaces/pressStart2p'
import cairo from '../fontfaces/cairo'

export const Themes = {
	SUNSET: {
		fontSize: '16px',
		'text-primary': '#FFFFFF',
		'text-accent': '#E5E5E5',
		reputation: '#62cc84',
		gr1: `#DA4453`,
		gr2: `#89216B`,
		fontFamily: "'Poppins', sans-serif",
		fontSrc: poppins,
		gold: 'gold',
		silver: '#C0C0C0',
		bronze: '#CD7F32',
	} as ThemeType,
	DARK: {
		'text-primary': '#FFF',
		'text-accent': '#ddd',
		fontSize: '16px',
		fontFamily: "'Poppins', sans-serif",
		fontSrc: poppins,
		reputation: '#62cc84',
		gr1: '#232526',
		gr2: '#414345',
		gold: 'gold',
		silver: '#C0C0C0',
		bronze: '#CD7F32',
	} as ThemeType,
	LIGHT: {
		'text-primary': '#000',
		'text-accent': '#212121',
		fontSize: '16px',
		fontFamily: "'Poppins', sans-serif",
		fontSrc: poppins,
		reputation: '#62cc84',
		gr1: '#E0EAFC',
		gr2: '#CFDEF3',
		gold: '#b89b00',
		silver: '#757575',
		bronze: '#bb8f4c',
	} as ThemeType,
	ELEGANT: {
		'text-primary': '#151515',
		'text-accent': '#222',
		reputation: '#4ed479',
		gr1: `#D3CCE3`,
		gr2: `#E9E4F0`,
		fontSize: '16px',
		fontFamily: "'Playfair Display', serif",
		fontSrc: playfairDisplay,
		gold: '#b89b00',
		silver: '#757575',
		bronze: '#bb8f4c',
	} as ThemeType,
	CYBERPUNK: {
		'text-primary': '#FFFFFF',
		'text-accent': '#E5E5E5',
		reputation: '#62cc84',
		gr1: `#333399`,
		gr2: `#89216B`,
		fontFamily: "'Cairo', sans-serif",
		fontSize: '16px',
		fontSrc: cairo,
		gold: 'gold',
		silver: '#C0C0C0',
		bronze: '#CD7F32',
	} as ThemeType,
	RETRO: {
		'text-primary': '#b5179e',
		'text-accent': '#a82395',
		reputation: '#52b788',
		gr1: '#141414',
		gr2: '#434343',
		fontFamily: "'Press Start 2P', cursive",
		fontSize: '12px',
		fontSrc: pressStart2p,
		gold: 'gold',
		silver: '#C0C0C0',
		bronze: '#CD7F32',
	} as ThemeType,
}
